# Generated by Django 4.0.4 on 2022-05-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0002_alter_itineraire_difficulte_estimee_sortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='photo1',
            field=models.ImageField(default='default.jpg', upload_to='photo/'),
        ),
    ]
