# Generated by Django 4.0.4 on 2022-04-26 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0002_alter_itineraire_difficulte_estimee_sortie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=200)),
                ('latitude_depart', models.FloatField()),
                ('longitude_depart', models.FloatField()),
                ('arrivee', models.CharField(max_length=200)),
                ('latitude_arrivee', models.FloatField()),
                ('longitude_arrivee', models.FloatField()),
                ('zone_geo_latitude', models.FloatField()),
                ('zone_geo_longitude', models.FloatField()),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
            ],
        ),
    ]
