# Generated by Django 4.0.4 on 2022-05-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0004_commentaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='date_sortie',
            new_name='date',
        ),
    ]
