# Generated by Django 4.0.4 on 2022-05-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0005_rename_date_sortie_commentaire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
