# Generated by Django 4.0.4 on 2022-05-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0007_alter_commentaire_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='statut',
            field=models.CharField(choices=[('PB', 'Public'), ('PR', 'Privé')], default='PB', max_length=2),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='photo1',
            field=models.ImageField(default='default.png', upload_to='photo/'),
        ),
    ]
