# Generated by Django 4.0.4 on 2022-05-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0008_alter_commentaire_statut_alter_sortie_photo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='photo1',
            field=models.ImageField(default='photo/default.png', upload_to='photo/'),
        ),
    ]
