# Generated by Django 4.0.4 on 2022-05-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0009_alter_sortie_photo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='photo2',
            field=models.ImageField(default='photo/default.png', upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='photo3',
            field=models.ImageField(default='photo/default.png', upload_to='photo/'),
        ),
    ]
