# Generated by Django 4.0.4 on 2022-05-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0010_sortie_photo2_sortie_photo3'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='cache',
            field=models.BooleanField(default=False),
        ),
    ]
